# Generated by Django 3.2.12 on 2022-07-26 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        
        migrations.CreateModel(
            name='books',
            fields=[
                ('bookid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=50, null=True)),
                ('bookauthor', models.CharField(max_length=50, null=True)),
                ('issuedate', models.DateField()),
                ('renewdate', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'retuned'), (0, 'not returned')], default=0, help_text=('1->returned', '0->not returned'))),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cs.student')),
            ],
        ),
    ]
