# Generated by Django 3.2.12 on 2022-08-02 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.CharField(max_length=20, null=True)),
                ('link', models.CharField(max_length=50, null=True)),
                ('by', models.CharField(max_length=20, null=True)),
                ('event_date', models.DateField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='laptop',
            fields=[
                ('lapid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('renew_date', models.DateField(null=True)),
                ('status', models.IntegerField(choices=[(0, 'Nill'), (1, 'retuned'), (2, 'not returned'), (3, 'reserved')], default=0, help_text=('3->reserved', '2->not returned', '1->returned', '0->Nill'))),
                ('staff_user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cs.staff')),
                ('student_user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cs.student')),
            ],
        ),
        migrations.CreateModel(
            name='books',
            fields=[
                ('bookid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=50, null=True)),
                ('bookauthor', models.CharField(max_length=50, null=True)),
                ('issuedate', models.DateField(blank=True, null=True)),
                ('renewdate', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('status', models.IntegerField(choices=[(3, 'Nill'), (2, 'reserved'), (1, 'retuned'), (0, 'not returned')], default=3, help_text=('3->Nill', '2->reserved,1->returned', '0->not returned'))),
                ('staff_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cs.staff')),
                ('student_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cs.student')),
            ],
        ),
    ]
