# Generated by Django 3.2.12 on 2022-07-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='issuedate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='renewdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
