# Generated by Django 3.2.12 on 2022-07-27 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0002_auto_20220726_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='laptop',
            fields=[
                ('lapid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('datel', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Nill'), (1, 'retuned'), (2, 'not returned')], default=0, help_text=('2->not returned', '1->returned'))),
                ('user', models.ForeignKey(blank=True, default='null', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cs.student')),
            ],
        ),
    ]
