# Generated by Django 3.2.12 on 2022-07-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0004_auto_20220730_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='status',
            field=models.IntegerField(choices=[(3, 'Nill'), (2, 'reserved'), (1, 'retuned'), (0, 'not returned')], default=3, help_text=('3->Nill', '2->reserved,1->returned', '0->not returned')),
        ),
    ]
