# Generated by Django 3.2.12 on 2022-08-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0005_alter_books_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
