# Generated by Django 3.2.12 on 2022-08-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0006_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='programme',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
