# Generated by Django 3.2.12 on 2022-08-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0007_events_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='link',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
