# Generated by Django 3.2.12 on 2022-08-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0009_events_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_date',
            field=models.DateField(null=True),
        ),
    ]
